# 秘钥
asekey : "sadasdasdsxcsa42"
jwtkey : "sfsrwewcweafa,sf"
# 端口
addr : 1234

# mysql connect configuration
mysql:
    username: root
    password: 'wsd20000117wsd'
    path: '127.0.0.1:3306'
    db-name: 'mooc'
    config: 'charset=utf8&parseTime=True&loc=Local'